#!/usr/bin/env bash

case $1 in

    engg | news)
    wd="tech/$1"
    ;;
    guide)
    wd="tech/$1s"
    ;;
    challenge)
    wd="coding/$1s"
    ;;
    generative)
    wd="coding/$1"
    ;;
    poem | write-up)
    wd="musings/$1s"
    ;;
    
esac

hugo new -k $1 $wd/$2.md
