#!/usr/bin/env bash

file_name=$2
case $1 in

    engg | news)
    wd="tech/$1"
    ;;
    guide)
    wd="tech/$1s"
    ;;
    challenge)
    wd="coding/$1s"
    ;;
    generative)
    wd="coding/$1"
    ;;
    log)
    wd="coding/100daysofcode"
    file_name="100-days-of-code-log-$2"
    ;;
    poem | write-up)
    wd="musings/$1s"
    ;;
    
esac

hugo new -k $1 $wd/$file_name.md
